baseURL = "https://astrascalla.com"
languageCode = "en-gb"
title = "Astrascalla - Radical Innovation"
enableEmoji = true
paginate = 5
theme = "hugo-clinic-notes"

[params]
  description = "Helping prepare civilization for the 22nd century by investing in paradigm shifts."

[[params.menu]]
  name = "about"
  url = "about/"

[[params.menu]]
  name = "writings"
  url = "writings/"

[[params.menu]]
  name = "mandatory reading"
  url = "mandatory-reading/"

[[params.menu]]
  name = "graphic"
  url = "https://www.are.na/astrascalla"

# If you want the table of contents at the top of individual notes to index
# further levels of header (default H2) set this to a higher number
[markup.goldmark.renderer]
    unsafe = true

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]
