baseURL = "https://astrascalla.com"
languageCode = "en-gb"
title = "Astrascalla - Radical Innovation"
enableEmoji = true
paginate = 5
theme = "hugo-clinic-notes"

[[params.menu]]
  name = "about"
  url = "about/"

[[params.menu]]
  name = "research (coming soon)"
  url = ""

# If you want the table of contents at the top of individual notes to index
# further levels of header (default H2) set this to a higher number
[markup.goldmark.renderer]
    unsafe = true

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]
